services:
  api1: &api
    image: ghcr.io/viniciusdsandrade/rinha-de-backend-2026:submission
    platform: linux/amd64
    environment:
      UNIX_SOCKET_PATH: /sockets/api1.sock
    networks:
      - backend
    volumes:
      - sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.44"
          memory: "165MB"

  api2:
    <<: *api
    environment:
      UNIX_SOCKET_PATH: /sockets/api2.sock

  nginx:
    image: nginx:1.27-alpine
    platform: linux/amd64
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.12"
          memory: "20MB"

networks:
  backend:
    driver: bridge

volumes:
  sockets:
